import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import apiClient from "../api/client";

type Order = { id: string; orderNumber: string; createdAt: string; customerName: string; total: number; paidAmount: number; debtAmount: number; status: string; paymentMethods: string };
type Detail = { orderNumber: string; createdAt: string; subtotal: number; discount: number; total: number; paidAmount: number; debtAmount: number; status: string; items: { productName: string; quantity: number; unitPrice: number; lineTotal: number }[] };

export default function Orders() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [detail, setDetail] = useState<Detail | null>(null);
  const [search, setSearch] = useState("");
  const [error, setError] = useState("");
  const load = async () => { try { const response = await apiClient.get("/pos/orders"); setOrders(response.data?.data ?? response.data ?? []); } catch (requestError: any) { setError(requestError.response?.data?.message ?? "Không thể tải lịch sử đơn hàng."); } };
  useEffect(() => { void load(); }, []);
  const open = async (id: string) => { try { const response = await apiClient.get(`/pos/orders/${id}`); setDetail(response.data?.data ?? response.data); } catch (requestError: any) { setError(requestError.response?.data?.message ?? "Không thể tải chi tiết đơn hàng."); } };
  const cancel = async (id: string) => { if (!window.confirm("Bạn có chắc muốn hủy đơn này?")) return; try { await apiClient.post(`/pos/orders/${id}/cancel`); await load(); setDetail(null); } catch (requestError: any) { setError(requestError.response?.data?.message ?? "Không thể hủy đơn hàng."); } };
  const visible = orders.filter(order => JSON.stringify(order).toLowerCase().includes(search.toLowerCase()));
  return <div className="operation-page"><header className="operation-header"><div><Link className="back-link" to="/pos">← Bán hàng</Link><h1>Lịch sử đơn hàng</h1><p>Đơn hàng và trạng thái thanh toán từ database.</p></div><div className="operation-actions"><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Tìm mã đơn, khách hàng..." /><button className="operation-refresh" onClick={() => void load()} aria-label="Tải lại">↻</button></div></header>{error && <div className="operation-error">{error}</div>}{visible.length === 0 ? <div className="operation-empty">Chưa có đơn hàng.</div> : <div className="operation-table order-table"><div className="operation-row operation-row-head"><span>Mã đơn</span><span>Thời gian</span><span>Khách hàng</span><span>Tổng tiền</span><span>Thanh toán</span></div>{visible.map(order => <button className="operation-row order-row" key={order.id} onClick={() => void open(order.id)}><span>{order.orderNumber}</span><span>{new Date(order.createdAt).toLocaleString("vi-VN")}</span><span>{order.customerName}</span><span>{order.total.toLocaleString("vi-VN")}đ</span><span><em className={order.status === "Cancelled" ? "stock-badge danger" : "stock-badge"}>{order.status}</em></span></button>)}</div>}{detail && <div className="order-detail"><div className="order-detail-head"><div><h2>{detail.orderNumber}</h2><small>{new Date(detail.createdAt).toLocaleString("vi-VN")} · {detail.status}</small></div><div><button className="operation-primary" onClick={() => window.print()}>In hóa đơn</button><button className="operation-refresh" onClick={() => void cancel(orders.find(order => order.orderNumber === detail.orderNumber)?.id ?? "")} disabled={detail.status === "Cancelled"}>Hủy đơn</button></div></div>{detail.items.map(item => <div className="order-detail-line" key={item.productName}><span>{item.productName} × {item.quantity}</span><b>{item.lineTotal.toLocaleString("vi-VN")}đ</b></div>)}<div className="order-detail-total"><span>Tạm tính</span><b>{detail.subtotal.toLocaleString("vi-VN")}đ</b><span>Giảm giá</span><b>-{detail.discount.toLocaleString("vi-VN")}đ</b><strong>Tổng cộng</strong><strong>{detail.total.toLocaleString("vi-VN")}đ</strong></div></div>}</div>;
}
